version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./public:/var/www/html/public
            - ./public/uploads/pages/images:/var/www/html/public/uploads/pages/images
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - dedirest-network

    nginx:
        image: nginx:alpine
        ports:
            - '8000:80'
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        depends_on:
            - app
        networks:
            - dedirest-network

    db:
        image: mysql:8.0
        platform: linux/arm64/v8
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - dedirest-network

networks:
    dedirest-network:
        driver: bridge

volumes:
    db_data:
    images_data:
